name: Sensu Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Download latest nagios plugins release
      run: curl -sL https://api.github.com/repos/nagios-plugins/nagios-plugins/releases/latest | grep "browser_download_url" | cut -d ":" -f "2,3" | tr -d \" | wget -qi -
    - name: Untar release
      run: tar -xzvf nagios-plugins-*.tar.gz
    - name: Do sensu stuff
      run: | 
        cd nagios-plugins-*/
        pwd
        ./configure
        make
        mv plugins bin
        find bin -type f ! -executable -delete
        tar -czpvf sensu-nagios-plugins.tar.gz bin/
        sha512sum sensu-nagios-plugins.tar.gz > sha512sum.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "sensu-nagios-plugins.tar.gz,sha512sum.txt"
